### ISSUE TITLE
The name minecraft.io is already taken by luxwander

### ISSUE THREAD

**Issue by 109C** [netraameht/minecraft.io#1]
Also, minecraft.io isn't a very descriptive name.

**Comment by dezemand** [comment]
That's just the domain name, but you're probably right about the name not being very descriptive. Any suggestions?

**Comment by 109C** [comment]
Possible ideas:
`d3.io`
`cubeleft`
`flyingmc`

I think d3.io is the best one, as it hasn't been taken yet.

**Comment by dezemand** [comment]
I'm keeping the current name for now, it's version 0.0.1 anyway, so it doesn't matter too much.
